# These are supported funding model platforms

github: [hivejs]
# patreon: hivejs
# open_collective: hive
# ko_fi: hivejs
# tidelift: npm/@hive/std
# community_bridge: hive
# liberapay: hivejs
# issuehunt: hivejs
# custom: ['https://hive.dev/sponsor']
